// Created by iWeb 3.0.4 local-build-20130317

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWEmptyStroke(),stroke_3:new IWStrokeParts([{rect:new IWRect(-4,3,6,443),url:'Harry_Walker_Benson_2_files/stroke_7.png'},{rect:new IWRect(-9,-10,0,0),url:null},{rect:new IWRect(2,-4,331,7),url:'Harry_Walker_Benson_2_files/stroke_8.png'},{rect:new IWRect(333,-3,5,6),url:'Harry_Walker_Benson_2_files/stroke_9.png'},{rect:new IWRect(333,3,7,443),url:'Harry_Walker_Benson_2_files/stroke_10.png'},{rect:new IWRect(333,446,7,6),url:'Harry_Walker_Benson_2_files/stroke_11.png'},{rect:new IWRect(2,446,331,6),url:'Harry_Walker_Benson_2_files/stroke_12.png'},{rect:new IWRect(-4,446,6,6),url:'Harry_Walker_Benson_2_files/stroke_13.png'}],new IWSize(337,449)),stroke_0:new IWEmptyStroke(),shadow_1:new IWShadow({blurRadius:10,offset:new IWPoint(4.2426,4.2426),color:'#000000',opacity:0.750000}),shadow_0:new IWShadow({blurRadius:10,offset:new IWPoint(4.2426,4.2426),color:'#000000',opacity:0.750000}),stroke_4:new IWStrokeParts([{rect:new IWRect(-4,3,5,54),url:'Harry_Walker_Benson_2_files/stroke_14.png'},{rect:new IWRect(-2,1,3,2),url:'Harry_Walker_Benson_2_files/stroke_15.png'},{rect:new IWRect(1,-4,410,7),url:'Harry_Walker_Benson_2_files/stroke_16.png'},{rect:new IWRect(411,-4,6,7),url:'Harry_Walker_Benson_2_files/stroke_17.png'},{rect:new IWRect(411,3,6,54),url:'Harry_Walker_Benson_2_files/stroke_18.png'},{rect:new IWRect(411,57,6,6),url:'Harry_Walker_Benson_2_files/stroke_19.png'},{rect:new IWRect(1,57,410,6),url:'Harry_Walker_Benson_2_files/stroke_20.png'},{rect:new IWRect(-4,57,5,6),url:'Harry_Walker_Benson_2_files/stroke_21.png'}],new IWSize(414,60)),stroke_2:new IWStrokeParts([{rect:new IWRect(-4,3,6,336),url:'Harry_Walker_Benson_2_files/stroke.png'},{rect:new IWRect(-10,-19,0,0),url:null},{rect:new IWRect(2,-4,329,7),url:'Harry_Walker_Benson_2_files/stroke_1.png'},{rect:new IWRect(331,-3,6,6),url:'Harry_Walker_Benson_2_files/stroke_2.png'},{rect:new IWRect(331,3,7,336),url:'Harry_Walker_Benson_2_files/stroke_3.png'},{rect:new IWRect(331,339,7,6),url:'Harry_Walker_Benson_2_files/stroke_4.png'},{rect:new IWRect(2,339,329,6),url:'Harry_Walker_Benson_2_files/stroke_5.png'},{rect:new IWRect(-4,339,6,6),url:'Harry_Walker_Benson_2_files/stroke_6.png'}],new IWSize(335,342))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Harry_Walker_Benson_2_files/Harry_Walker_Benson_2Moz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
