// Created by iWeb 3.0.4 local-build-20130316

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,326),url:'Leckies_of_Stirlingshire_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'Leckies_of_Stirlingshire_files/stroke_9.png'},{rect:new IWRect(2,-2,383,4),url:'Leckies_of_Stirlingshire_files/stroke_10.png'},{rect:new IWRect(385,-2,4,4),url:'Leckies_of_Stirlingshire_files/stroke_11.png'},{rect:new IWRect(385,2,4,326),url:'Leckies_of_Stirlingshire_files/stroke_12.png'},{rect:new IWRect(385,328,4,4),url:'Leckies_of_Stirlingshire_files/stroke_13.png'},{rect:new IWRect(2,328,383,4),url:'Leckies_of_Stirlingshire_files/stroke_14.png'},{rect:new IWRect(-2,328,4,4),url:'Leckies_of_Stirlingshire_files/stroke_15.png'}],new IWSize(387,330)),stroke_3:new IWStrokeParts([{rect:new IWRect(-4,3,6,124),url:'Leckies_of_Stirlingshire_files/stroke_24.png'},{rect:new IWRect(-2,1,4,2),url:'Leckies_of_Stirlingshire_files/stroke_25.png'},{rect:new IWRect(2,-4,327,7),url:'Leckies_of_Stirlingshire_files/stroke_26.png'},{rect:new IWRect(329,-4,7,7),url:'Leckies_of_Stirlingshire_files/stroke_27.png'},{rect:new IWRect(329,3,7,124),url:'Leckies_of_Stirlingshire_files/stroke_28.png'},{rect:new IWRect(329,127,7,6),url:'Leckies_of_Stirlingshire_files/stroke_29.png'},{rect:new IWRect(2,127,327,6),url:'Leckies_of_Stirlingshire_files/stroke_30.png'},{rect:new IWRect(-4,127,6,6),url:'Leckies_of_Stirlingshire_files/stroke_31.png'}],new IWSize(333,130)),stroke_2:new IWStrokeParts([{rect:new IWRect(-2,2,4,292),url:'Leckies_of_Stirlingshire_files/stroke_16.png'},{rect:new IWRect(-2,-2,4,4),url:'Leckies_of_Stirlingshire_files/stroke_17.png'},{rect:new IWRect(2,-2,218,4),url:'Leckies_of_Stirlingshire_files/stroke_18.png'},{rect:new IWRect(220,-2,4,4),url:'Leckies_of_Stirlingshire_files/stroke_19.png'},{rect:new IWRect(220,2,4,292),url:'Leckies_of_Stirlingshire_files/stroke_20.png'},{rect:new IWRect(220,294,4,4),url:'Leckies_of_Stirlingshire_files/stroke_21.png'},{rect:new IWRect(2,294,218,4),url:'Leckies_of_Stirlingshire_files/stroke_22.png'},{rect:new IWRect(-2,294,4,4),url:'Leckies_of_Stirlingshire_files/stroke_23.png'}],new IWSize(222,296)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,221),url:'Leckies_of_Stirlingshire_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'Leckies_of_Stirlingshire_files/stroke_1.png'},{rect:new IWRect(2,-2,221,4),url:'Leckies_of_Stirlingshire_files/stroke_2.png'},{rect:new IWRect(223,-2,4,4),url:'Leckies_of_Stirlingshire_files/stroke_3.png'},{rect:new IWRect(223,2,4,221),url:'Leckies_of_Stirlingshire_files/stroke_4.png'},{rect:new IWRect(223,223,4,4),url:'Leckies_of_Stirlingshire_files/stroke_5.png'},{rect:new IWRect(2,223,221,4),url:'Leckies_of_Stirlingshire_files/stroke_6.png'},{rect:new IWRect(-2,223,4,4),url:'Leckies_of_Stirlingshire_files/stroke_7.png'}],new IWSize(225,225))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Leckies_of_Stirlingshire_files/Leckies_of_StirlingshireMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
