// Created by iWeb 3.0.4 local-build-20130322

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-6,5,11,277),url:'Mary_Ann_Taylor_%26_James_Leckey_files/stroke.png'},{rect:new IWRect(-5,-5,10,10),url:'Mary_Ann_Taylor_%26_James_Leckey_files/stroke_1.png'},{rect:new IWRect(5,-6,194,11),url:'Mary_Ann_Taylor_%26_James_Leckey_files/stroke_2.png'},{rect:new IWRect(199,-5,10,10),url:'Mary_Ann_Taylor_%26_James_Leckey_files/stroke_3.png'},{rect:new IWRect(199,5,10,277),url:'Mary_Ann_Taylor_%26_James_Leckey_files/stroke_4.png'},{rect:new IWRect(199,282,9,10),url:'Mary_Ann_Taylor_%26_James_Leckey_files/stroke_5.png'},{rect:new IWRect(5,282,194,11),url:'Mary_Ann_Taylor_%26_James_Leckey_files/stroke_6.png'},{rect:new IWRect(-5,282,10,10),url:'Mary_Ann_Taylor_%26_James_Leckey_files/stroke_7.png'}],new IWSize(204,288)),shadow_0:new IWShadow({blurRadius:10,offset:new IWPoint(4.2426,4.2426),color:'#000000',opacity:0.750000}),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,296),url:'Mary_Ann_Taylor_%26_James_Leckey_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'Mary_Ann_Taylor_%26_James_Leckey_files/stroke_9.png'},{rect:new IWRect(2,-2,221,4),url:'Mary_Ann_Taylor_%26_James_Leckey_files/stroke_10.png'},{rect:new IWRect(223,-2,4,4),url:'Mary_Ann_Taylor_%26_James_Leckey_files/stroke_11.png'},{rect:new IWRect(223,2,4,296),url:'Mary_Ann_Taylor_%26_James_Leckey_files/stroke_12.png'},{rect:new IWRect(223,298,4,4),url:'Mary_Ann_Taylor_%26_James_Leckey_files/stroke_13.png'},{rect:new IWRect(2,298,221,4),url:'Mary_Ann_Taylor_%26_James_Leckey_files/stroke_14.png'},{rect:new IWRect(-2,298,4,4),url:'Mary_Ann_Taylor_%26_James_Leckey_files/stroke_15.png'}],new IWSize(225,300))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Mary_Ann_Taylor_&_James_Leckey_files/Mary_Ann_Taylor_&_James_LeckeyMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
