// Created by iWeb 3.0.4 local-build-20130316

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,199),url:'James_Benson_%26_Elizabeth_Hayward_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'James_Benson_%26_Elizabeth_Hayward_files/stroke_9.png'},{rect:new IWRect(2,-2,235,4),url:'James_Benson_%26_Elizabeth_Hayward_files/stroke_10.png'},{rect:new IWRect(237,-2,4,4),url:'James_Benson_%26_Elizabeth_Hayward_files/stroke_11.png'},{rect:new IWRect(237,2,4,199),url:'James_Benson_%26_Elizabeth_Hayward_files/stroke_12.png'},{rect:new IWRect(237,201,4,5),url:'James_Benson_%26_Elizabeth_Hayward_files/stroke_13.png'},{rect:new IWRect(2,201,235,5),url:'James_Benson_%26_Elizabeth_Hayward_files/stroke_14.png'},{rect:new IWRect(-2,201,4,5),url:'James_Benson_%26_Elizabeth_Hayward_files/stroke_15.png'}],new IWSize(239,203)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,326),url:'James_Benson_%26_Elizabeth_Hayward_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'James_Benson_%26_Elizabeth_Hayward_files/stroke_1.png'},{rect:new IWRect(2,-2,383,4),url:'James_Benson_%26_Elizabeth_Hayward_files/stroke_2.png'},{rect:new IWRect(385,-2,4,4),url:'James_Benson_%26_Elizabeth_Hayward_files/stroke_3.png'},{rect:new IWRect(385,2,4,326),url:'James_Benson_%26_Elizabeth_Hayward_files/stroke_4.png'},{rect:new IWRect(385,328,4,4),url:'James_Benson_%26_Elizabeth_Hayward_files/stroke_5.png'},{rect:new IWRect(2,328,383,4),url:'James_Benson_%26_Elizabeth_Hayward_files/stroke_6.png'},{rect:new IWRect(-2,328,4,4),url:'James_Benson_%26_Elizabeth_Hayward_files/stroke_7.png'}],new IWSize(387,330))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('James_Benson_&_Elizabeth_Hayward_files/James_Benson_&_Elizabeth_HaywardMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');fixAllIEPNGs('Media/transparent.gif');applyEffects()}
